### ISSUE TITLE
Allow an author to choose a px value not to be converted to rem

### ISSUE THREAD

**Issue by kaelig** [robwierzbowski/node-pixrem#11]
Sometimes an author might not want a value to scale up according to user zoom (which is the main benefit of rem units).

Example: icons build a sprite background. Icon size & background-position should be in `px` only.

There should be a way to prevent node-pixrem from transforming a value at a granular level.
### Syntax proposition

``` css
.icon {
  background-position: 50px -20px /* no-pixrem */;
}
```

Let me know what you think.
