### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by MoOx** [robwierzbowski/node-pixrem#25]
Input.css

```css
body {
  color: red;

  font-size: 1rem;
  line-height: 1.5rem;
}
```

output.css

```css
body {
  color: red;

  font-size: 16px;

  font-size: 1rem;
  line-height: 24px;
  line-height: 1.5rem;
}
```

This is kind of weird and unexpected. @ai any words on this ?
