### ISSUE TITLE
Error with nested rules

### ISSUE THREAD

**Issue by ai** [robwierzbowski/node-pixrem#41]
Input:

```css
a {
  b {
    margin-top: 2rem;
  }
}
```

Output:

```css
a {
    margin-top: 32px;
  b {
    margin-top: 2rem;
  }
}
```

/cc @MoOx because this plugin is in cssnext
