### ISSUE TITLE
Values are not rounded properly

### ISSUE THREAD

**Issue by jedmao** [robwierzbowski/node-pixrem#44]
For example, I have a root value of `14px` and the following CSS:

```css
.foo {   
    font: 300 1.14286rem/1.28571rem 'Source Sans Pro', Arial, sans-serif;
}
```

Which transpiles into:

```css
.foo {
    font: 300 16px/17px 'Source Sans Pro', Arial, sans-serif;
}
```

But `14px * 1.28571 === 17.99994`. I would expect `16px/18px` instead.
