### ISSUE TITLE
NaNpx values when font-size is set on the html element

### ISSUE THREAD

**Issue by dotnetCarpenter** [robwierzbowski/node-pixrem#45]
I have posted this issue in [cssnext#210](https://github.com/cssnext/cssnext/issues/210) but feel that it really belongs here.

`cat node_modules/pixrem/package.json | grep version`: `"version": "2.0.0",`
`node_modules/.bin/postcss -v`: `postcss version 5.0.4`

Thanks to @ben-eb I have reduced a test case that reproduce the issue.
Running `postcss`/`pixrem` with the following command:
`node_modules/.bin/postcss -u pixrem` and/or `node_modules/.bin/cssnext`

Smaller test case:
```css
html {
  font-size: 0.625vw;
}

h1 {
  font-size: 6rem;
}
```

Output:
```css
html {
  font-size: 0.625vw;
}

h1 {
  font-size: NaNpx; /* only happens when font-size is set on the html element */
  font-size: 6rem;
}
```
