### ISSUE TITLE
Rem units on border-radius aren't changed to pixels

### ISSUE THREAD

**Issue by dustinwilson** [robwierzbowski/node-pixrem#50]
This:

```css
div {
    border-radius: 1rem;
    height: 30rem;
}
```

produces:

```css
div {
    border-radius: 1rem;
    height: 480px;
    height: 30rem;
}
```

instead of:

```css
div {
    border-radius: 16px;
    border-radius: 1rem;
    height: 480px;
    height: 30rem;
}
```
